// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresApp;

namespace kern.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190321122940_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("kern.Models.DataBase.AccauntUser", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastEntry");

                    b.Property<string>("Login");

                    b.Property<string>("UserName");

                    b.Property<bool>("isValid");

                    b.HasKey("IdUser");

                    b.ToTable("AccauntUsers");
                });

            modelBuilder.Entity("kern.Models.DataBase.OilField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<bool>("isNotValid");

                    b.HasKey("Id");

                    b.ToTable("OilFields");
                });
#pragma warning restore 612, 618
        }
    }
}
