// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresApp;

namespace kern.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190328125446_5")]
    partial class _5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("kern.Models.DataBase.AccauntRole", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("RoleName");

                    b.Property<bool>("isValid");

                    b.HasKey("IdRole");

                    b.ToTable("AccauntRoles");
                });

            modelBuilder.Entity("kern.Models.DataBase.AccauntUser", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Email");

                    b.Property<bool>("IsValid");

                    b.Property<string>("Login");

                    b.Property<string>("UserName");

                    b.HasKey("IdUser");

                    b.ToTable("AccauntUsers");
                });

            modelBuilder.Entity("kern.Models.DataBase.AccauntUsersRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccauntUser");

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("IdRole");

                    b.HasKey("Id");

                    b.HasIndex("AccauntUser");

                    b.ToTable("AccauntUsersRoles");
                });

            modelBuilder.Entity("kern.Models.DataBase.OilField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<bool>("isNotValid");

                    b.HasKey("Id");

                    b.ToTable("OilFields");
                });

            modelBuilder.Entity("kern.Models.DataBase.AccauntUsersRole", b =>
                {
                    b.HasOne("kern.Models.DataBase.AccauntUser", "IdUser")
                        .WithMany()
                        .HasForeignKey("AccauntUser");
                });
#pragma warning restore 612, 618
        }
    }
}
